export default {
    'lustrous-text': 'Lustrous',
    'counting-number': 'Counting Number',
    'distort-text': 'Distort Text',
    'draw-line-text': 'Draw Line Text',
    'scramble-text': 'Scramble Text',
    'sliding-number': 'Sliding Number',
    'text-splitting': 'Splitting Text',
    'text-gradient': 'Text Gradient',
    'text-highlight': 'Text Highlight',
    'text-rotator': 'Text Rotator',
    'text-roller': 'Text Roller',
    'text-squash': 'Text Squash',
    'word-cascade': 'Word Cascade',
}
