export default {
    CardSwap: 'Card Swap',
    badges: 'Badges',
    buttons: 'Buttons',
    carousels: 'Carousels',
    codeblock: 'CodeBlock',
    'date-time': 'Date Time',
    disclosure: 'Disclosures',
    dropdown: 'Dropdowns',
    form: 'Form',
    glassicons: 'Glass Icons',
    kbd: 'KBD',
    preview: 'Preview Block',
    stepper: 'Stepper',
    switch: 'Switch',
    text: 'Text',
    tooltips: 'Tooltips',
}
